apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: orn8qmrch-python 
  janus-idp.io/tekton: orn8qmrch-python
  backstage.io/kubernetes-id: orn8qmrch-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: orn8qmrch-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml