apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: orn8qmrch-python-gitops
  description: This is GitOps manifest for orn8qmrch-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=orn8qmrch-python
    backstage.io/kubernetes-id: orn8qmrch-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: orn8qmrch-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:orn8qmrch-python
