apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: orn8qmrch-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: orn8qmrch-python 
  name: orn8qmrch-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: orn8qmrch-python 
